import { useState } from "react";
import { KeyRound, Loader2, Mic, Wand2 } from "lucide-react";
import { scenesNeedingAudio, type Project, type RenderJob } from "@app/core";
import { toast } from "sonner";
import { Button } from "@/components/ui/button.tsx";
import { Input } from "@/components/ui/input.tsx";
import { Label } from "@/components/ui/label.tsx";
import { Slider } from "@/components/ui/slider.tsx";
import { Progress } from "@/components/ui/progress.tsx";
import { ScrollArea } from "@/components/ui/scroll-area.tsx";
import { Separator } from "@/components/ui/separator.tsx";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select.tsx";
import { BgmSection } from "@/components/bgm-section.tsx";
import { CaptionsSection } from "@/components/captions-section.tsx";
import { useSettings, useUpdateSettings, useVoices } from "@/hooks/useSettings.ts";
import { useJobStream } from "@/hooks/useJob.ts";
import { api, ApiError, projectFileUrl } from "@/lib/api.ts";
import { formatDuration } from "@/lib/format.ts";

function ApiKeyPrompt() {
  const [key, setKey] = useState("");
  const updateSettings = useUpdateSettings();

  async function save() {
    if (key.trim().length === 0) return;
    try {
      await updateSettings.mutateAsync({ providers: { elevenlabs: { apiKey: key.trim() } } });
      setKey("");
      toast.success("ElevenLabs key saved");
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : "Couldn't save the key");
    }
  }

  return (
    <div className="border-border/70 space-y-3 rounded-lg border border-dashed p-6">
      <div className="flex items-center gap-2">
        <KeyRound className="text-muted-foreground h-4 w-4" />
        <p className="text-sm font-medium">ElevenLabs API key needed</p>
      </div>
      <p className="text-muted-foreground text-xs">
        Voiceover is generated by ElevenLabs. The key is stored on this machine in
        <code className="mx-1">~/VideoStudio/settings.json</code>
        and never leaves the server.
      </p>
      <div className="flex gap-2">
        <Input
          type="password"
          value={key}
          placeholder="sk_…"
          onChange={(e) => setKey(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter") void save();
          }}
        />
        <Button onClick={save} disabled={key.trim().length === 0 || updateSettings.isPending}>
          {updateSettings.isPending ? "Saving…" : "Save"}
        </Button>
      </div>
    </div>
  );
}

export function AudioTab({
  project,
  onUpdate,
  onJobFinished,
}: {
  project: Project;
  onUpdate: (patch: Partial<Pick<Project, "voice" | "captions" | "bgm">>) => void;
  /** Pulls server-written scene.audio back into the editor draft. */
  onJobFinished: () => void;
}) {
  const { data: settings } = useSettings();
  const configured = settings?.providers.elevenlabs.configured ?? false;
  const {
    data: voices,
    isLoading: voicesLoading,
    error: voicesError,
  } = useVoices(project.voice.providerId, configured);
  const [starting, setStarting] = useState(false);

  const { job, watch, isRunning } = useJobStream(project.id, (finished: RenderJob) => {
    if (finished.state === "done") toast.success("Voiceover ready");
    if (finished.state === "error") toast.error(finished.error ?? "Voiceover failed");
    onJobFinished();
  });

  const stale = scenesNeedingAudio(project);
  const withAudio = project.scenes.filter((s) => s.audio);

  async function generate(force: boolean) {
    setStarting(true);
    try {
      const started = await api.generateTts(project.id, force ? { force: true } : {});
      watch(started.id);
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : "Couldn't start voiceover");
    } finally {
      setStarting(false);
    }
  }

  return (
    <div className="space-y-6 p-6">
      {!configured && <ApiKeyPrompt />}

      <div className="grid gap-4 sm:grid-cols-2">
        <div className="space-y-2">
          <Label htmlFor="voice">Voice</Label>
          <Select
            value={project.voice.voiceId || undefined}
            disabled={!configured || voicesLoading}
            onValueChange={(voiceId) => onUpdate({ voice: { ...project.voice, voiceId } })}
          >
            <SelectTrigger id="voice">
              <SelectValue
                placeholder={
                  !configured ? "Add an API key first" : voicesLoading ? "Loading voices…" : "Pick a voice"
                }
              />
            </SelectTrigger>
            <SelectContent>
              {(voices ?? []).map((voice) => (
                <SelectItem key={voice.id} value={voice.id}>
                  {voice.name}
                  {voice.labels.accent ? ` · ${voice.labels.accent}` : ""}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {/* Surface the provider's own message (e.g. a 401) rather than a
              guess — a wrong key is the most likely cause and the user can
              only fix it if we say so. */}
          {configured && voicesError && (
            <p className="text-destructive text-xs">
              {voicesError instanceof ApiError ? voicesError.message : "Couldn't load voices."}
            </p>
          )}
          {configured && !voicesLoading && !voicesError && (voices ?? []).length === 0 && (
            <p className="text-muted-foreground text-xs">
              No voices in this ElevenLabs account yet.
            </p>
          )}
        </div>

        <div className="space-y-4">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>Speed</Label>
              <span className="text-muted-foreground text-xs tabular-nums">
                {project.voice.speed.toFixed(2)}×
              </span>
            </div>
            <Slider
              min={0.7}
              max={1.2}
              step={0.05}
              value={[project.voice.speed]}
              onValueChange={([speed]) =>
                onUpdate({ voice: { ...project.voice, speed: speed ?? project.voice.speed } })
              }
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>Stability</Label>
              <span className="text-muted-foreground text-xs tabular-nums">
                {project.voice.stability.toFixed(2)}
              </span>
            </div>
            <Slider
              min={0}
              max={1}
              step={0.05}
              value={[project.voice.stability]}
              onValueChange={([stability]) =>
                onUpdate({ voice: { ...project.voice, stability: stability ?? project.voice.stability } })
              }
            />
            <p className="text-muted-foreground text-xs">
              Lower is more expressive, higher is more consistent.
            </p>
          </div>
        </div>
      </div>

      <Separator />

      <div className="space-y-3">
        <div className="flex flex-wrap items-center gap-2">
          <Button
            onClick={() => void generate(false)}
            disabled={!configured || isRunning || starting || stale.length === 0}
          >
            {isRunning || starting ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Wand2 className="h-4 w-4" />
            )}
            {stale.length === 0
              ? "Everything is voiced"
              : `Generate ${stale.length} missing`}
          </Button>
          <Button
            variant="outline"
            onClick={() => void generate(true)}
            disabled={!configured || isRunning || starting || project.scenes.every((s) => !s.text.trim())}
          >
            Regenerate all
          </Button>
          {isRunning && (
            <Button variant="ghost" onClick={() => job && void api.cancelJob(job.id)}>
              Cancel
            </Button>
          )}
        </div>

        {/* Changing the voice or a script line marks scenes stale — nothing is
            re-charged for scenes that already match their hash. */}
        <p className="text-muted-foreground text-xs">
          Scenes are only re-generated when their script or voice settings changed.
        </p>

        {job && (
          <div className="space-y-2 rounded-md border p-3">
            <div className="flex items-center justify-between text-xs">
              <span className="capitalize">{job.state}</span>
              <span className="text-muted-foreground tabular-nums">{Math.round(job.progress * 100)}%</span>
            </div>
            <Progress value={job.progress * 100} />
            {job.error && <p className="text-destructive text-xs">{job.error}</p>}
            {job.log.length > 0 && (
              <ScrollArea className="h-24">
                <pre className="text-muted-foreground font-mono text-[11px] whitespace-pre-wrap">
                  {job.log.join("\n")}
                </pre>
              </ScrollArea>
            )}
          </div>
        )}
      </div>

      <Separator />

      <BgmSection project={project} onUpdate={onUpdate} />

      <Separator />

      <CaptionsSection project={project} onUpdate={onUpdate} />

      {withAudio.length > 0 && (
        <div className="space-y-2">
          <Label>Generated voiceover</Label>
          <div className="space-y-2">
            {project.scenes.map((scene, index) =>
              scene.audio ? (
                <div key={scene.id} className="flex items-center gap-3 rounded-md border p-2">
                  <Mic className="text-muted-foreground h-3 w-3 shrink-0" />
                  <span className="text-muted-foreground w-6 shrink-0 text-xs tabular-nums">{index + 1}</span>
                  <audio
                    controls
                    preload="none"
                    className="h-8 flex-1"
                    src={projectFileUrl(project.slug, scene.audio.file)}
                  />
                  <span className="text-muted-foreground shrink-0 text-xs tabular-nums">
                    {formatDuration(scene.audio.durationMs)}
                  </span>
                </div>
              ) : null,
            )}
          </div>
        </div>
      )}
    </div>
  );
}
